$ErrorActionPreference = 'Stop'
Set-Location -LiteralPath $PSScriptRoot

if (-not (Get-Command docker -ErrorAction SilentlyContinue)) {
    throw 'Docker CLI was not found. Open Docker Desktop and install/enable Docker Compose.'
}
& docker info | Out-Null
if ($LASTEXITCODE -ne 0) {
    throw 'Docker Desktop is not reachable from this PowerShell session. Start Docker Desktop, wait until it says Running, then rerun this script.'
}

if (-not (Test-Path -LiteralPath '.env')) {
    $rng = [System.Security.Cryptography.RandomNumberGenerator]::Create()
    $rootBytes = [byte[]]::new(48)
    $appBytes = [byte[]]::new(48)
    $rng.GetBytes($rootBytes)
    $rng.GetBytes($appBytes)
    $rootSecret = [Convert]::ToBase64String($rootBytes).TrimEnd('=').Replace('+', 'x').Replace('/', 'y')
    $appSecret = [Convert]::ToBase64String($appBytes).TrimEnd('=').Replace('+', 'u').Replace('/', 'v')
    $rng.Dispose()
    @(
        '# Local-only secrets generated by Start-Local.ps1; ignored by Git.'
        "DB_ROOT_PASSWORD=$rootSecret"
        "DB_APP_PASSWORD=$appSecret"
        'APP_PORT=8081'
    ) | Set-Content -LiteralPath '.env' -Encoding ascii
    [Array]::Clear($rootBytes, 0, $rootBytes.Length)
    [Array]::Clear($appBytes, 0, $appBytes.Length)
}

& docker compose up --build -d
if ($LASTEXITCODE -ne 0) { throw 'Compose could not start. Share the error output; do not post the local .env file.' }
& docker compose ps
