@extends('layouts.portal')
@section('title', 'Portal accounts · New Cruse Academy')
@section('content')
<div class="portal-shell"><header class="portal-header"><a class="portal-brand" href="{{ route('dashboard') }}"><img src="{{ asset('images/school-logo.png') }}" alt="" class="header-logo"><span>New Cruse Academy</span></a><div class="account-actions"><span>{{ auth()->user()->name }} <small>Administrator</small></span><form method="post" action="{{ route('logout') }}">@csrf<button class="button button-light">Sign out</button></form></div></header><main class="dashboard-main"><a class="action-link" href="{{ route('dashboard') }}">← Dashboard</a><p class="eyebrow">ACCOUNT ACCESS</p><h1>Teacher and parent accounts</h1><p class="muted">Create login access for an existing staff or parent profile. The temporary password is displayed once; share it directly with that person.</p>
@if($login=session('new_login'))<div class="setup-note"><strong>Temporary login created for {{ $login['name'] }}</strong><span>Email: <b>{{ $login['email'] }}</b><br>Temporary password: <code>{{ $login['password'] }}</code><br>They must change it at first sign-in. Copy it now; it is not emailed or saved in this page after the session.</span></div>@endif
@if($errors->any())<div class="form-errors"><ul>@foreach($errors->all() as $error)<li>{{ $error }}</li>@endforeach</ul></div>@endif
<section class="dashboard-grid"><article class="dashboard-card"><h2>Teachers</h2><div class="table-wrap"><table class="data-table"><thead><tr><th>Name / email</th><th>Login</th><th>Action</th></tr></thead><tbody>@forelse($staff as $profile)<tr><td>{{ $profile->person->first_name }} {{ $profile->person->last_name }}<br><small>{{ $profile->email ?? 'Email needed' }}</small></td><td>{{ $profile->person->user ? ucfirst($profile->person->user->account_status) : 'No login' }}</td><td>@if(!$profile->person->user && $profile->email)<form method="post" action="{{ route('accounts.create') }}">@csrf<input type="hidden" name="profile_type" value="teacher"><input type="hidden" name="profile_id" value="{{ $profile->id }}"><button class="button button-primary">Create login</button></form>@endif</td></tr>@empty<tr><td colspan="3">No active teacher profiles.</td></tr>@endforelse</tbody></table></div></article>
<article class="dashboard-card"><h2>Parents</h2><div class="table-wrap"><table class="data-table"><thead><tr><th>Name / email</th><th>Login</th><th>Action</th></tr></thead><tbody>@forelse($parents as $profile)<tr><td>{{ $profile->person->first_name }} {{ $profile->person->last_name }}<br><small>{{ $profile->email ?? 'Email needed' }}</small></td><td>{{ $profile->person->user ? ucfirst($profile->person->user->account_status) : 'No login' }}</td><td>@if(!$profile->person->user && $profile->email)<form method="post" action="{{ route('accounts.create') }}">@csrf<input type="hidden" name="profile_type" value="parent"><input type="hidden" name="profile_id" value="{{ $profile->id }}"><button class="button button-primary">Create login</button></form>@endif</td></tr>@empty<tr><td colspan="3">No active parent profiles.</td></tr>@endforelse</tbody></table></div></article></section></main></div>
@endsection
